# Generated by Django 3.0.4 on 2020-06-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='所在国')),
                ('country_eng', models.CharField(max_length=30, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Dojos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojo_name', models.CharField(max_length=50, verbose_name='道場')),
                ('dojo_name_eng', models.CharField(max_length=50, verbose_name='Dojo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinsa.Country', verbose_name='所在国')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=70, verbose_name='イベント名')),
                ('event_date', models.DateField(verbose_name='開催日')),
                ('marker1', models.CharField(max_length=25, verbose_name='審査員1')),
                ('marker2', models.CharField(max_length=25, verbose_name='審査員2')),
                ('marker3', models.CharField(max_length=25, verbose_name='審査員3')),
                ('marker4', models.CharField(max_length=25, verbose_name='審査員4')),
                ('marker5', models.CharField(max_length=25, verbose_name='審査員5')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=4, verbose_name='段位')),
                ('grade_name_eng', models.CharField(max_length=30, verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='状態')),
                ('status_eng', models.CharField(max_length=20, verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='Testee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testee_name', models.CharField(max_length=20, verbose_name='氏名')),
                ('testee_name_eng', models.CharField(max_length=20, verbose_name='Name')),
                ('first_grade', models.DateField(blank=True, null=True, verbose_name='初段取得日')),
                ('second_grade', models.DateField(blank=True, null=True, verbose_name='二段取得日')),
                ('third_grade', models.DateField(blank=True, null=True, verbose_name='三段取得日')),
                ('fourth_grade', models.DateField(blank=True, null=True, verbose_name='四段取得日')),
                ('fifth_grade', models.DateField(blank=True, null=True, verbose_name='五段取得日')),
                ('sixth_grade', models.DateField(blank=True, null=True, verbose_name='六段取得日')),
                ('renshi', models.DateField(blank=True, null=True, verbose_name='練士取得日')),
                ('seventh_grade', models.DateField(blank=True, null=True, verbose_name='七段取得日')),
                ('kyoshi', models.DateField(blank=True, null=True, verbose_name='教士取得日')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinsa.Dojos', verbose_name='道場')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinsa.Grade', verbose_name='受審段位')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinsa.Status', verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='Scoringsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.FloatField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0), (5.5, 5.5), (6.0, 6.0), (6.5, 6.5), (7.0, 7.0), (7.5, 7.5), (8.0, 8.0), (8.5, 8.5), (9.0, 9.0), (9.5, 9.5), (10.0, 10.0)], default=0.0, verbose_name='審査員１')),
                ('score2', models.FloatField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0), (5.5, 5.5), (6.0, 6.0), (6.5, 6.5), (7.0, 7.0), (7.5, 7.5), (8.0, 8.0), (8.5, 8.5), (9.0, 9.0), (9.5, 9.5), (10.0, 10.0)], default=0.0, verbose_name='審査員２')),
                ('score3', models.FloatField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0), (5.5, 5.5), (6.0, 6.0), (6.5, 6.5), (7.0, 7.0), (7.5, 7.5), (8.0, 8.0), (8.5, 8.5), (9.0, 9.0), (9.5, 9.5), (10.0, 10.0)], default=0.0, verbose_name='審査員３')),
                ('score4', models.FloatField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0), (5.5, 5.5), (6.0, 6.0), (6.5, 6.5), (7.0, 7.0), (7.5, 7.5), (8.0, 8.0), (8.5, 8.5), (9.0, 9.0), (9.5, 9.5), (10.0, 10.0)], default=0.0, verbose_name='審査員４')),
                ('score5', models.FloatField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0), (5.5, 5.5), (6.0, 6.0), (6.5, 6.5), (7.0, 7.0), (7.5, 7.5), (8.0, 8.0), (8.5, 8.5), (9.0, 9.0), (9.5, 9.5), (10.0, 10.0)], default=0.0, verbose_name='審査員５')),
                ('pratical_points', models.FloatField(default=0.0, verbose_name='実技得点')),
                ('written_points', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=0, verbose_name='筆記得点')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinsa.Events', verbose_name='受審催事')),
                ('testee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shinsa.Testee', verbose_name='受審者')),
            ],
        ),
    ]
