# Generated by Django 3.0.4 on 2020-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='dojo_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='道場番号'),
        ),
    ]
