# Generated by Django 3.0.4 on 2020-06-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testee',
            name='grade',
        ),
        migrations.AddField(
            model_name='scoringsheet',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shinsa.Grade', verbose_name='受審段位'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_eng',
            field=models.CharField(max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='fifth_grade',
            field=models.DateField(blank=True, null=True, verbose_name='五段取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='first_grade',
            field=models.DateField(blank=True, null=True, verbose_name='初段取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='fourth_grade',
            field=models.DateField(blank=True, null=True, verbose_name='四段取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='kyoshi',
            field=models.DateField(blank=True, null=True, verbose_name='教士取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='renshi',
            field=models.DateField(blank=True, null=True, verbose_name='練士取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='second_grade',
            field=models.DateField(blank=True, null=True, verbose_name='二段取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='seventh_grade',
            field=models.DateField(blank=True, null=True, verbose_name='七段取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='sixth_grade',
            field=models.DateField(blank=True, null=True, verbose_name='六段取得日(yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='third_grade',
            field=models.DateField(blank=True, null=True, verbose_name='三段取得日(yyyy-mm-dd)'),
        ),
    ]
