# Generated by Django 3.0.4 on 2020-07-04 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinsa', '0002_auto_20200702_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='dojo_name',
            field=models.CharField(max_length=50, verbose_name='道場名'),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='dojo_name_eng',
            field=models.CharField(max_length=50, verbose_name='Dojo Name'),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='dojo_number',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Four digits'), django.core.validators.RegexValidator('^[0-9]*$', 'only number')], verbose_name='道場番号'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='membership_number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(7, 'Seven digits'), django.core.validators.RegexValidator('^[0-9]*$', 'only number')], verbose_name='会員番号'),
        ),
        migrations.AlterField(
            model_name='testee',
            name='testee_name',
            field=models.CharField(max_length=20, verbose_name='Name Japanese'),
        ),
    ]
