# Generated by Django 3.0.4 on 2022-01-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinsa', '0004_auto_20200723_0916'),
        ('shinsa', '0004_auto_20200723_1735'),
    ]

    operations = [
    ]
